Repository salesforce/endgame, pull requests merged in 2021-02, with the labels that each got.

#55 Fixes #52 - list-resources and smash enumerates resources in all regions
  .readthedocs.yml
  docs/requirements-docs.txt
  endgame/bin/version.py
  endgame/command/list_resources.py
  endgame/command/smash.py
  endgame/shared/aws_login.py
  endgame/shared/resource_results.py
  endgame/shared/validate.py
  test/shared/test_resource_results.py
Labels: enhancement

#56 Small README edits and suggestions
  README.md
Labels: cla:signed

#57 Update README
  README.md
  docs/index.md
  endgame/bin/cli.py
Labels: documentation

#59 Resolve issue with expose.py environment variable
  endgame/command/expose.py
Labels: cla:signed
